# Site wide configuration

title: Kevin's
locale: ko_KR
url: 
https_url: https://sungwoo.me

lang: ko
language_names:
  en: English
  ko: 한국어

# Jekyll configuration
permalink:   /posts/:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - octopress-multilingual
  - jekyll-redirect-from

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
#  name: Kevin
  avatar: sungwoo-bio.jpg
#  bio: "NAVER에서 iOS 앱을 개발하며 살고 있는 평범한 개발자입니다. 여행, 스노우보드 그리고 뻘짓에 대해 덕후입니다. 항상 덕력계발에 힘쓰고 있습니다."
  email: choo@sungwoo.me
  disqus-shortname: kswchoo
  twitter: kswchoo
  facebook: kswchoo
  google:
    plus: #username
    analytics: UA-44212597-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: kswchoo
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: sungwoo
  xing: #username
  instagram: kswchoo
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
